import * as dotenv from 'dotenv';
dotenv.config();

const configEnv = {
  app: {
    PORT: process.env.PORT,
    ENVIRONMENT: process.env.ENVIRONMENT,
    NEXT_PUBLIC_CANONICAL_ROOT_URL: process.env.NEXT_PUBLIC_CANONICAL_ROOT_URL,
    NEXT_PUBLIC_MARKETPLACE_NAME: process.env.NEXT_PUBLIC_MARKETPLACE_NAME,
    NEXT_PUBLIC_LOCALE: process.env.NEXT_PUBLIC_LOCALE,
    NEXT_PUBLIC_TWITTER_HANDLE: process.env.NEXT_PUBLIC_TWITTER_HANDLE,
  },
  AWS: {
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
    AWS_REGION: process.env.AWS_REGION,
  },
  db: {
    DATABASE_HOST: process.env.DATABASE_HOST || 'localhost',
    DATABASE_PORT: parseInt(process.env.DATABASE_PORT!) || 5432,
    DATABASE_USERNAME: process.env.DATABASE_USERNAME,
    DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
    DATABASE_NAME: process.env.DATABASE_NAME,
    LOCAL_DATABASE_HOST: process.env.LOCAL_DATABASE_HOST || 'localhost',
    LOCAL_DATABASE_PORT: parseInt(process.env.LOCAL_DATABASE_PORT!) || 5432,
    LOCAL_DATABASE_USERNAME: process.env.LOCAL_DATABASE_USERNAME,
    LOCAL_DATABASE_PASSWORD: process.env.LOCAL_DATABASE_PASSWORD,
    LOCAL_DATABASE_NAME: process.env.LOCAL_DATABASE_NAME,
    PRODUCTION_DATABASE_HOST:
      process.env.PRODUCTION_DATABASE_HOST || 'localhost',
    PRODUCTION_DATABASE_PORT:
      parseInt(process.env.PRODUCTION_DATABASE_PORT!) || 5432,
    PRODUCTION_DATABASE_USERNAME: process.env.PRODUCTION_DATABASE_USERNAME,
    PRODUCTION_DATABASE_PASSWORD: process.env.PRODUCTION_DATABASE_PASSWORD,
    PRODUCTION_DATABASE_NAME: process.env.PRODUCTION_DATABASE_NAME,
  },
  mailchimp: {
    MAILCHIMP_API_KEY: process.env.MAILCHIMP_API_KEY,
    MAILCHIMP_DOMAIN: process.env.MAILCHIMP_DOMAIN,
    MAILCHIMP_LIST_ID: process.env.MAILCHIMP_LIST_ID,
  },
  sendgrid: {
    API_KEY: process.env.SENDGRID_API_KEY,
    SENDER_EMAIL: process.env.SENDGRID_SENDER_EMAIL,
  },
  google: {
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID as string,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET as string,
    NEXT_PUBLIC_GOOGLE_ANALYTICS_MEASUREMENT_ID: process.env
      .NEXT_PUBLIC_GOOGLE_ANALYTICS_MEASUREMENT_ID as string,
    NEXT_PUBLIC_GOOGLE_ANALYTICS_STREAM_ID: process.env
      .NEXT_PUBLIC_GOOGLE_ANALYTICS_STREAM_ID as string,
  },
};

export default configEnv;
